runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.png
  static_files: imgs/favicon.png
  upload: imgs/favicon.png

- url: /apple-touch-icon.png
  static_files: imgs/favicon.png
  upload: imgs/favicon.png

- url: /.*
  script: rsstodolist.app

